/* =========================================================
   Machine FX engine
   ---------------------------------------------------------
   A tiny runtime for one-off "reactions" the machine can have
   when a particular movie is loaded into a slot. Reactions are
   keyed by TMDB movie id and live in fx/cues-*.js "packs"; this
   file only provides the plumbing:

     - MachineFX.register([...cues])  add cues (keyed by TMDB id)
     - MachineFX.packs({ name: [ids] })
                                      which pack holds which ids
                                      (fx/index.js, generated by
                                      tools/build-fx-index.js)
     - MachineFX.onMovieAdded(movie, slotIndex)
                                      called by the app after a
                                      movie lands in a slot

   Packs are loaded lazily: nothing but this engine, the shared art
   and the id index is fetched up front. A pack's script is only
   requested the first time one of its movies is added.

   A cue looks like:
     {
       id: 550,                  // TMDB id (or an array of ids)
       y: 1999,                  // optional release year; if the added
                                 // movie's TMDB year is known and is more
                                 // than two years off, the cue is skipped
       run: async (fx) => {...}  // the reaction itself
     }

   Sound: cues call fx.sfx(name, opts) / fx.sfxSeq(steps), which play
   from the synthesized library in fx/sound.js (MachineSound). Sound is
   deliberately rare - most cues are silent.
   fx.sfx("clip:1", { fallback: "sting" }) plays this movie's recorded
   clip fx/clips/<tmdb id>-1.mp3 instead (or the fallback sound when the
   clip can't be played). A cue that uses clips lists them as
   clips: ["1"] so they're fetched while the cue is still waiting to start.

   A cue fires every time its movie is added. fx.stats.adds says how
   many times that movie has been added on this device, for cues that
   want to vary with repeat visits.

   Everything here is decorative. Nothing touches app state, and
   every failure is swallowed so adding a movie can never break.
   ========================================================= */
(function () {
  "use strict";

  const MEMORY_KEY = "mvm-fx-memory";
  const MAX_RUN_MS = 15000;
  const ABORT = { aborted: true };
  const PAGE_PARTS = ["body > header", "body > .machine", "body > .cta-stage", "#watchedBtn", "body > footer"];

  const cues = new Map();
  const packOf = new Map();
  const packLoads = {};
  let current = null;
  let latestAdd = 0;

  // Where the packs live (next to this script) and which build they are.
  const scriptSrc = (document.currentScript && document.currentScript.src) || "fx/engine.js";
  const PACK_BASE = scriptSrc.replace(/[^/]*$/, "");
  const PACK_VERSION = (/[?&]v=([^&]+)/.exec(scriptSrc) || [])[1] || "";
  // Recorded clips live in fx/clips/, named by TMDB id: fx/clips/<id>-<key>.mp3.
  // Clip files are never edited in place (a new take gets a new key), so their
  // URLs carry no version and stay cached across app updates.
  const clipSrc = (id, key) => PACK_BASE + "clips/" + Number(id) + "-" + String(key).replace(/[^\w-]/g, "") + ".mp3";

  const prefersReduced = () =>
    !!(window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches);

  // ---------- memory (per-device add counts) ----------
  function loadMemory() {
    try {
      return JSON.parse(localStorage.getItem(MEMORY_KEY)) || {};
    } catch (e) {
      return {};
    }
  }
  function saveMemory(mem) {
    try {
      localStorage.setItem(MEMORY_KEY, JSON.stringify(mem));
    } catch (e) {
      // storage full/blocked - counts just won't persist
    }
  }

  // ---------- sound ----------
  // All audio goes through fx/sound.js (MachineSound); cues reach it via
  // fx.sfx()/fx.sfxSeq(), which tie each sound to the cue's lifetime.
  const NO_SOUND = { stop() {}, get playing() { return false; } };

  const NOTE_INDEX = { C: -9, D: -7, E: -5, F: -4, G: -2, A: 0, B: 2 };
  function noteFreq(n) {
    if (typeof n === "number") return n;
    const m = /^([A-G])([#b]?)(-?\d)$/.exec(n);
    if (!m) return 440;
    let semis = NOTE_INDEX[m[1]] + (m[2] === "#" ? 1 : m[2] === "b" ? -1 : 0) + (parseInt(m[3], 10) - 4) * 12;
    return 440 * Math.pow(2, semis / 12);
  }

  // ---------- the layer every effect draws into ----------
  function layer() {
    let el = document.getElementById("fx-layer");
    if (!el) {
      el = document.createElement("div");
      el.id = "fx-layer";
      el.setAttribute("aria-hidden", "true");
      document.body.appendChild(el);
    }
    return el;
  }

  const rand = (a, b) => a + Math.random() * (b - a);
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

  // A cue may start a wait/tween without awaiting it; when the cue ends
  // those reject with ABORT. Mark them handled so that is never reported.
  function quiet(p) {
    p.catch(() => {});
    return p;
  }

  // ---------- the toolkit handed to each cue ----------
  function makeFx(movie, slotIndex, stats) {
    const cleanups = [];
    const waiters = new Set();
    const nodes = new Set();
    let aborted = false;
    let forced = false;
    const reduced = prefersReduced();

    const fx = {
      movie,
      stats,
      slotIndex,
      reduced,
      rand,
      pick,
      note: noteFreq,
      get aborted() {
        return aborted;
      },

      // --- timing ---
      wait(ms) {
        return quiet(new Promise((resolve, reject) => {
          if (aborted) return reject(ABORT);
          const w = { reject };
          w.t = setTimeout(() => {
            waiters.delete(w);
            resolve();
          }, ms);
          waiters.add(w);
        }));
      },
      // Calls fn(progress 0..1) every frame for ms. Abort-aware.
      tween(ms, fn, ease) {
        return quiet(new Promise((resolve, reject) => {
          if (aborted) return reject(ABORT);
          const t0 = performance.now();
          const e = ease || ((p) => p);
          const w = { reject };
          waiters.add(w);
          const step = (now) => {
            if (aborted) return;
            const p = Math.max(0, Math.min(1, (now - t0) / ms));
            try { fn(e(p)); } catch (err) {}
            if (p < 1) w.t = requestAnimationFrame(step);
            else { waiters.delete(w); resolve(); }
          };
          w.t = requestAnimationFrame(step);
          w.raf = true;
        }));
      },
      later(ms, fn) {
        fx.wait(ms).then(() => {
          try { fn(); } catch (e) { /* a cue bug - never let it escape */ }
        }, () => {});
      },
      onCleanup(fn) {
        cleanups.push(fn);
      },

      // --- lookup ---
      $(sel) {
        return typeof sel === "string" ? document.querySelector(sel) : sel;
      },
      $$(sel) {
        return Array.from(document.querySelectorAll(sel));
      },
      slot() {
        return document.querySelectorAll("#grid .slot")[slotIndex] || null;
      },
      otherSlots(filledOnly) {
        return fx.$$("#grid .slot").filter((s, i) => i !== slotIndex && (!filledOnly || !s.classList.contains("empty")));
      },
      rect(el) {
        el = fx.$(el);
        if (el && typeof el.x === "number" && !el.getBoundingClientRect) {
          const w = el.width || 0, h = el.height || 0;
          return { left: el.x - w / 2, top: el.y - h / 2, width: w, height: h, x: el.x, y: el.y };
        }
        if (!el) return { left: innerWidth / 2 - 40, top: innerHeight / 2 - 60, width: 80, height: 120, x: innerWidth / 2, y: innerHeight / 2 };
        const r = el.getBoundingClientRect();
        return { left: r.left, top: r.top, width: r.width, height: r.height, x: r.left + r.width / 2, y: r.top + r.height / 2 };
      },
      pageParts() {
        return PAGE_PARTS.map((s) => document.querySelector(s)).filter(Boolean);
      },

      // --- DOM helpers (everything is removed on cleanup) ---
      node(html, opts) {
        opts = opts || {};
        const el = document.createElement(opts.tag || "div");
        if (opts.cls) el.className = opts.cls;
        if (html) el.innerHTML = html;
        if (opts.style) Object.assign(el.style, opts.style);
        (opts.parent ? fx.$(opts.parent) : layer()).appendChild(el);
        nodes.add(el);
        if (opts.ms) fx.later(opts.ms, () => fx.remove(el));
        return el;
      },
      remove(el) {
        if (el && el.parentNode) el.parentNode.removeChild(el);
        nodes.delete(el);
      },
      // Places a node centered on a fixed-layer point.
      put(html, x, y, opts) {
        opts = opts || {};
        const size = opts.size || 60;
        const el = fx.node(html, Object.assign({}, opts, {
          style: Object.assign({
            position: "absolute",
            left: x - size / 2 + "px",
            top: y - size / 2 + "px",
            width: size + "px",
            height: (opts.h || size) + "px"
          }, opts.style || {})
        }));
        el.classList.add("fx-sprite");
        return el;
      },
      cls(target, name, ms) {
        const els = typeof target === "string" ? fx.$$(target) : [].concat(target).filter(Boolean);
        els.forEach((el) => el.classList.add(name));
        const undo = () => els.forEach((el) => el.classList.remove(name));
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
        return els;
      },
      style(target, props, ms) {
        const els = typeof target === "string" ? fx.$$(target) : [].concat(target).filter(Boolean);
        const saved = els.map((el) => {
          const old = {};
          Object.keys(props).forEach((k) => (old[k] = el.style[k]));
          Object.assign(el.style, props);
          return [el, old];
        });
        const undo = () => saved.forEach(([el, old]) => Object.assign(el.style, old));
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
        return undo;
      },
      text(target, str, ms) {
        const el = fx.$(target);
        if (!el) return () => {};
        const old = el.textContent;
        el.textContent = str;
        let done = false;
        const undo = () => {
          if (done) return;
          done = true;
          if (el.isConnected) el.textContent = old;
        };
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
        return undo;
      },
      marquee(str, ms, sub) {
        fx.text(".machine-marquee .marquee-text", str, ms);
        if (sub !== undefined) fx.text(".machine-marquee .marquee-sub", sub, ms);
      },

      // --- motion (Web Animations; cancelled on cleanup) ---
      anim(target, frames, opts) {
        const els = typeof target === "string" ? fx.$$(target) : [].concat(target).filter(Boolean);
        const anims = els.filter((el) => el.animate).map((el) => {
          const a = el.animate(frames, Object.assign({ fill: "forwards" }, typeof opts === "number" ? { duration: opts } : opts));
          cleanups.push(() => {
            try { a.cancel(); } catch (e) {}
          });
          return a;
        });
        return Promise.all(anims.map((a) => a.finished.catch(() => {})));
      },
      // Motion that should simply not happen for reduced-motion users.
      move(target, frames, opts) {
        if (reduced) return Promise.resolve();
        return fx.anim(target, frames, opts);
      },
      fadeIn(el, ms) {
        return fx.anim(el, [{ opacity: 0 }, { opacity: 1 }], { duration: ms || 250, fill: "forwards" });
      },
      fadeOut(el, ms) {
        return fx.anim(el, [{ opacity: 1 }, { opacity: 0 }], { duration: ms || 300, fill: "forwards" });
      },
      shake(level, ms) {
        if (reduced) return Promise.resolve();
        const px = level === "lg" ? 9 : level === "md" ? 5 : 2.5;
        const n = Math.max(3, Math.round((ms || 400) / 50));
        const frames = [];
        for (let i = 0; i < n; i++) {
          const f = 1 - i / n;
          frames.push({ transform: "translate(" + rand(-px, px) * f + "px," + rand(-px, px) * f + "px)" });
        }
        frames.push({ transform: "translate(0,0)" });
        return fx.anim(fx.pageParts(), frames, { duration: ms || 400, easing: "steps(" + n + ")", fill: "none" });
      },
      page(frames, opts) {
        return fx.move(fx.pageParts(), frames, opts);
      },
      // Sprite that travels between two points (px, layer coordinates).
      // Reduced motion: it just appears at the midpoint and fades.
      fly(html, from, to, opts) {
        opts = opts || {};
        const size = opts.size || 60;
        const el = fx.put(html, 0, 0, Object.assign({}, opts, { style: Object.assign({ left: "0px", top: "0px" }, opts.style || {}) }));
        const dur = opts.dur || 1500;
        if (reduced) {
          const mx = (from[0] + to[0]) / 2 - size / 2;
          const my = (from[1] + to[1]) / 2 - (opts.h || size) / 2;
          el.style.transform = "translate(" + mx + "px," + my + "px)";
          return fx.anim(el, [{ opacity: 0 }, { opacity: 1, offset: 0.2 }, { opacity: 1, offset: 0.8 }, { opacity: 0 }], { duration: dur }).then(() => fx.remove(el));
        }
        const mid = opts.via;
        const frame = (p, r) =>
          ({ transform: "translate(" + (p[0] - size / 2) + "px," + (p[1] - (opts.h || size) / 2) + "px) rotate(" + (r || 0) + "deg)" + (opts.flip ? " scaleX(-1)" : "") });
        const frames = mid ? [frame(from, opts.r0), frame(mid, opts.r1), frame(to, opts.r2)] : [frame(from, opts.r0), frame(to, opts.r2)];
        return fx.anim(el, frames, { duration: dur, easing: opts.easing || "linear" }).then(() => {
          if (!opts.keep) fx.remove(el);
          return el;
        });
      },

      // --- screen-wide treatments ---
      filter(css, ms, opts) {
        opts = opts || {};
        const el = fx.node("", { cls: "fx-filter", style: { backdropFilter: css, webkitBackdropFilter: css, background: opts.bg || "transparent" } });
        if (opts.fade && !reduced) fx.fadeIn(el, opts.fade);
        if (ms) {
          fx.later(ms - (opts.fade || 0), () => {
            if (opts.fade && !reduced) fx.fadeOut(el, opts.fade).then(() => fx.remove(el));
            else fx.remove(el);
          });
        }
        return el;
      },
      wash(color, ms, opts) {
        opts = opts || {};
        const el = fx.node("", { cls: "fx-filter", style: { background: color, mixBlendMode: opts.blend || "normal", opacity: opts.opacity == null ? 1 : opts.opacity } });
        if (opts.fade) fx.fadeIn(el, opts.fade);
        if (ms) {
          fx.later(ms - (opts.fade || 0), () => {
            if (opts.fade) fx.fadeOut(el, opts.fade).then(() => fx.remove(el));
            else fx.remove(el);
          });
        }
        return el;
      },
      // Photosensitivity: flashes are single, softened under reduced motion.
      flash(color, ms) {
        const el = fx.node("", { cls: "fx-filter", style: { background: color || "#fff" } });
        const dur = ms || 220;
        return fx.anim(el, [{ opacity: reduced ? 0.35 : 0.95 }, { opacity: 0 }], { duration: reduced ? dur * 2 : dur, easing: "ease-out" }).then(() => fx.remove(el));
      },
      letterbox(ms, size) {
        const h = size || "11vh";
        const top = fx.node("", { cls: "fx-bar", style: { top: 0, height: h } });
        const bot = fx.node("", { cls: "fx-bar", style: { bottom: 0, height: h } });
        if (!reduced) {
          fx.anim(top, [{ transform: "translateY(-100%)" }, { transform: "none" }], 300);
          fx.anim(bot, [{ transform: "translateY(100%)" }, { transform: "none" }], 300);
        }
        if (ms) fx.later(ms, () => { fx.remove(top); fx.remove(bot); });
        return [top, bot];
      },
      pillarbox(ms, size) {
        const w = size || "12vw";
        const l = fx.node("", { cls: "fx-bar", style: { left: 0, top: 0, bottom: 0, width: w, height: "auto" } });
        const r = fx.node("", { cls: "fx-bar", style: { right: 0, top: 0, bottom: 0, width: w, height: "auto", left: "auto" } });
        if (!reduced) {
          fx.anim(l, [{ transform: "translateX(-100%)" }, { transform: "none" }], 300);
          fx.anim(r, [{ transform: "translateX(100%)" }, { transform: "none" }], 300);
        }
        if (ms) fx.later(ms, () => { fx.remove(l); fx.remove(r); });
      },
      caption(str, opts) {
        opts = opts || {};
        const el = fx.node("", { cls: "fx-caption fx-cap-" + (opts.style || "subtitle"), style: opts.css || {} });
        el.textContent = str;
        if (opts.at === "slot" && fx.slot()) {
          const r = fx.rect(fx.slot());
          Object.assign(el.style, { left: r.x + "px", top: r.top + r.height + 6 + "px", bottom: "auto", transform: "translateX(-50%)" });
        }
        fx.fadeIn(el, 180);
        if (opts.ms) fx.later(opts.ms, () => fx.fadeOut(el, 250).then(() => fx.remove(el)));
        return el;
      },
      // Overlays the glass case (the grid of slots).
      glass(html, opts) {
        opts = opts || {};
        const grid = document.getElementById("grid");
        if (!grid) return null;
        const el = fx.node(html, { cls: "fx-glass " + (opts.cls || ""), parent: grid, style: opts.style });
        if (opts.ms) fx.later(opts.ms, () => fx.remove(el));
        return el;
      },
      // Adds temporary SVG artwork inside a mascot, in its own coordinates.
      costume(sel, svg, ms) {
        const host = fx.$(sel);
        if (!host) return null;
        const g = document.createElementNS("http://www.w3.org/2000/svg", "g");
        g.setAttribute("class", "fx-costume");
        g.innerHTML = svg;
        host.appendChild(g);
        nodes.add(g);
        if (ms) fx.later(ms, () => fx.remove(g));
        return g;
      },

      // --- particles ---
      // kind: "fall" | "rise" | "burst" | "drift" | "sweep"
      particles(opts) {
        opts = opts || {};
        const W = innerWidth, H = innerHeight;
        let count = opts.count || 20;
        if (reduced) count = Math.max(3, Math.round(count / 3));
        const dur = opts.dur || 2200;
        const origin = opts.from ? fx.rect(opts.from) : null;
        const area = opts.area ? fx.rect(opts.area) : { left: 0, top: 0, width: W, height: H };
        const all = [];
        for (let i = 0; i < count; i++) {
          const glyph = Array.isArray(opts.glyphs) ? pick(opts.glyphs) : (opts.glyphs || "");
          const size = rand(opts.min || 10, opts.max || 22);
          const el = fx.node(typeof glyph === "function" ? glyph(i) : glyph, { cls: "fx-particle" + (opts.cls ? " " + opts.cls : "") });
          el.style.width = el.style.height = size + "px";
          el.style.fontSize = size + "px";
          if (opts.colors) el.style.setProperty("--c", pick(opts.colors));
          let x0, y0, x1, y1;
          const kind = opts.kind || "fall";
          if (kind === "fall") {
            x0 = rand(area.left - 20, area.left + area.width); y0 = area.top + rand(-60, -10) * (opts.area ? 0.2 : 1);
            x1 = x0 + rand(-60, 60) * (opts.area ? 0.3 : 1) + (opts.wind || 0); y1 = area.top + area.height + (opts.area ? 0 : 40);
          } else if (kind === "rise") {
            x0 = origin ? origin.x + rand(-origin.width / 2, origin.width / 2) : rand(area.left, area.left + area.width);
            y0 = origin ? origin.y : area.top + area.height + 20;
            x1 = x0 + rand(-60, 60) + (opts.wind || 0); y1 = origin ? origin.y - rand(H * 0.3, H * 0.8) : -60;
          } else if (kind === "burst") {
            const o = origin || { x: W / 2, y: H / 2 };
            const a = rand(0, Math.PI * 2), d = rand(opts.spread || 60, (opts.spread || 60) * 2.4);
            x0 = o.x; y0 = o.y; x1 = o.x + Math.cos(a) * d; y1 = o.y + Math.sin(a) * d + (opts.gravity || 0);
          } else if (kind === "sweep") {
            const ltr = opts.dir !== "rtl";
            x0 = ltr ? -40 : W + 40; y0 = rand(area.top, area.top + area.height); x1 = ltr ? W + 40 : -40; y1 = y0 + rand(-80, 80);
          } else {
            x0 = rand(area.left, area.left + area.width); y0 = rand(area.top, area.top + area.height); x1 = x0 + rand(-50, 50); y1 = y0 + rand(-60, 20);
          }
          const d = dur * rand(0.7, 1.3);
          const delay = rand(0, opts.stagger == null ? dur * 0.5 : opts.stagger);
          const spin = opts.spin ? rand(-opts.spin, opts.spin) : 0;
          el.style.transform = "translate(" + x0 + "px," + y0 + "px)";
          if (reduced) {
            el.style.transform = "translate(" + (x0 + x1) / 2 + "px," + Math.min(H - 30, Math.max(10, (y0 + y1) / 2)) + "px)";
            all.push(fx.anim(el, [{ opacity: 0 }, { opacity: 1 }, { opacity: 0 }], { duration: d, delay, fill: "both" }));
          } else {
            all.push(fx.anim(el, [
              { transform: "translate(" + x0 + "px," + y0 + "px) rotate(0deg)", opacity: opts.fadeIn ? 0 : 1 },
              { opacity: 1, offset: 0.15 },
              { opacity: opts.keepOpacity ? 1 : 0.9, offset: 0.8 },
              { transform: "translate(" + x1 + "px," + y1 + "px) rotate(" + spin + "deg)", opacity: 0 }
            ], { duration: d, delay, easing: opts.easing || (kind === "burst" ? "cubic-bezier(.2,.7,.4,1)" : "linear"), fill: "both" }));
          }
          all[all.length - 1].then(() => fx.remove(el));
        }
        return Promise.all(all);
      },

      // --- sound ---
      // fx.sfx("clunk", { at: 300, vol: 0.6 }) plays a sound from the
      // library in fx/sound.js. `at` (ms) waits on the cue's own clock, so
      // it is cancelled with the cue and stays in step with its visuals.
      // Returns a handle with stop(ms) for loops and long sounds.
      // When the cue finishes, loops fade out and one-shots ring out; when
      // a cue is interrupted (another movie, tab hidden) everything stops.
      sfx(name, opts) {
        opts = opts || {};
        const S = window.MachineSound;
        if (!S || aborted) return NO_SOUND;
        if (/^clip:/.test(name)) {
          opts = Object.assign({}, opts, { src: clipSrc(movie && movie.id, name.slice(5)) });
          name = "clip";
        }
        const h = {
          inner: null,
          stopped: false,
          stop(ms) {
            h.stopped = true;
            if (h.inner) h.inner.stop(ms);
          },
          get playing() {
            return !!(h.inner && h.inner.playing);
          }
        };
        const go = () => {
          if (aborted || h.stopped) return;
          h.inner = S.play(name, opts);
        };
        if (opts.at > 0) fx.later(opts.at, go);
        else go();
        cleanups.push(() => {
          if (forced) h.stop(60);
          else if (opts.dur || opts.loop) h.stop(opts.fadeOut != null ? opts.fadeOut : 220);
        });
        return h;
      },
      // fx.sfxSeq([["motor", 0], ["clunk", 350, { vol: 0.8 }]]) - offsets
      // are ms from now.
      sfxSeq(steps) {
        return (steps || []).map((st) => fx.sfx(st[0], Object.assign({}, st[2], { at: (st[1] || 0) + ((st[2] && st[2].at) || 0) })));
      },

      // Older cues wrote their own inline synthesis with these. They are
      // retired (silent) so that sound stays deliberate and rare; seq()
      // still reports its length because some cues time visuals off it.
      tone() {},
      seq(notes, opts) {
        opts = opts || {};
        const beat = opts.beat || 0.18;
        return (notes || []).reduce((t, st) => t + beat * ((st && st[1]) || 1), opts.at || 0);
      },
      chord() {},
      noise() {},
      thud() {},
      click() {},

      // --- haptics (Android/Chrome; silently ignored elsewhere) ---
      buzz(pattern) {
        try {
          if (navigator.vibrate) navigator.vibrate(pattern);
        } catch (e) {}
      },

      // --- whole-page tricks ---
      // Freezes every running CSS/Web animation on the page.
      freeze(ms) {
        const anims = document.getAnimations ? document.getAnimations().filter((a) => a.playState === "running") : [];
        anims.forEach((a) => { try { a.pause(); } catch (e) {} });
        const undo = () => anims.forEach((a) => { try { if (a.playState === "paused") a.play(); } catch (e) {} });
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
        return undo;
      },
      // Slows (or speeds) every running animation on the page.
      tempo(rate, ms) {
        const anims = document.getAnimations ? document.getAnimations().filter((a) => a.playState === "running") : [];
        anims.forEach((a) => { try { a.updatePlaybackRate ? a.updatePlaybackRate(rate) : (a.playbackRate = rate); } catch (e) {} });
        const undo = () => anims.forEach((a) => { try { a.playbackRate = 1; } catch (e) {} });
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
      },
      // Runs fn on the next tap anywhere within `ms`. Never blocks the tap.
      onNextTap(fn, ms) {
        let armed = true;
        const h = (e) => {
          if (!armed) return;
          armed = false;
          document.removeEventListener("pointerdown", h, true);
          try { fn(e); } catch (err) {}
        };
        document.addEventListener("pointerdown", h, true);
        const undo = () => { armed = false; document.removeEventListener("pointerdown", h, true); };
        cleanups.push(undo);
        if (ms) fx.later(ms, undo);
      },

      // --- internals ---
      _abort(interrupted) {
        if (aborted) return;
        aborted = true;
        forced = !!interrupted;
        waiters.forEach((w) => { if (w.raf) cancelAnimationFrame(w.t); else clearTimeout(w.t); w.reject(ABORT); });
        waiters.clear();
        fx._cleanup();
      },
      _cleanup() {
        while (cleanups.length) {
          try { cleanups.pop()(); } catch (e) {}
        }
        nodes.forEach((n) => { if (n.parentNode) n.parentNode.removeChild(n); });
        nodes.clear();
      }
    };
    return fx;
  }

  function stopCurrent() {
    if (current) {
      current._abort(true);
      current = null;
    }
    document.documentElement.classList.remove("fx-running");
  }

  async function play(cue, fx) {
    stopCurrent();
    current = fx;
    document.documentElement.classList.add("fx-running");
    let timeout;
    try {
      await Promise.race([
        Promise.resolve().then(() => cue.run(fx)),
        new Promise((resolve) => { timeout = setTimeout(resolve, cue.maxMs || MAX_RUN_MS); })
      ]);
    } catch (e) {
      // aborted or a cue bug - either way just tidy up
    } finally {
      clearTimeout(timeout);
      if (current === fx) {
        // also cancels any timers the cue left armed, so nothing it
        // scheduled can fire after the tidy-up
        fx._abort();
        current = null;
        document.documentElement.classList.remove("fx-running");
      }
    }
  }

  function loadPack(name) {
    if (!packLoads[name]) {
      packLoads[name] = new Promise((resolve) => {
        const s = document.createElement("script");
        s.src = PACK_BASE + name + ".js" + (PACK_VERSION ? "?v=" + PACK_VERSION : "");
        s.async = true;
        s.onload = () => resolve(true);
        s.onerror = () => {
          delete packLoads[name];
          s.remove();
          resolve(false);
        };
        document.head.appendChild(s);
      });
    }
    return packLoads[name];
  }

  async function findCue(id) {
    if (cues.has(id)) return cues.get(id);
    const pack = packOf.get(id);
    if (!pack) return null;
    await loadPack(pack);
    return cues.get(id) || null;
  }

  // A cheap guard against a mistyped id: when both years are known and
  // clearly disagree, this isn't the movie the cue was written for.
  function yearMatches(cue, movie) {
    if (!cue.y) return true;
    const y = parseInt(movie && movie.year, 10);
    if (!y) return true;
    return Math.abs(y - cue.y) <= 2;
  }

  async function onMovieAdded(movie, slotIndex) {
    try {
      const id = Number(movie && movie.id);
      if (!id || (!cues.has(id) && !packOf.has(id))) return;
      const token = ++latestAdd;
      const cue = await findCue(id);
      if (!cue || token !== latestAdd || !yearMatches(cue, movie)) return;
      const mem = loadMemory();
      const adds = ((mem[id] && mem[id].a) || 0) + 1;
      mem[id] = { a: adds };
      saveMemory(mem);
      const fx = makeFx(movie, slotIndex, { adds });
      if (cue.clips && window.MachineSound) [].concat(cue.clips).forEach((k) => window.MachineSound.preload(clipSrc(id, k)));
      // Let the slot finish rendering its new poster first.
      setTimeout(() => play(cue, fx), cue.delay != null ? cue.delay : 250);
    } catch (e) {
      // never let a reaction interfere with adding a movie
    }
  }

  function packs(map) {
    Object.keys(map || {}).forEach((name) => {
      (map[name] || []).forEach((id) => packOf.set(Number(id), name));
    });
  }

  function register(list) {
    [].concat(list).forEach((cue) => {
      if (!cue || typeof cue.run !== "function") return;
      [].concat(cue.id).forEach((id) => cues.set(Number(id), cue));
    });
  }

  document.addEventListener("visibilitychange", () => {
    if (document.hidden) stopCurrent();
  });

  window.MachineFX = { register, packs, onMovieAdded };
})();
